# Generated by Django 3.2.9 on 2021-12-12 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shareconf", "0003_auto_20211208_1300"),
        ("sharecontributions", "0003_auto_20211211_2307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="contribType",
            field=models.CharField(
                choices=[("time", "Time"), ("expenses", "Expenses")], max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="projectType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shareconf.project"
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
