# Generated by Django 3.2.9 on 2022-01-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sharecontributions", "0006_rename_projecttype_contribution_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contribution",
            old_name="slices",
            new_name="shares",
        ),
    ]
