# Generated by Django 3.2.9 on 2021-11-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(default='creation', max_length=1024)),
                ('user', models.CharField(max_length=1024)),
                ('details', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserPie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('jobTitle', models.CharField(max_length=1024)),
                ('yearSalary', models.IntegerField(default=0)),
                ('well', models.FloatField(default=0)),
                ('slices', models.FloatField(default=0)),
            ],
        ),
    ]
