# Generated by Django 3.2.9 on 2021-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("type", models.CharField(default="creation", max_length=1024)),
                ("user", models.CharField(max_length=1024)),
                ("details", models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="jobTitle",
            field=models.CharField(default="hello", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="slices",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="well",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="yearSalary",
            field=models.IntegerField(default=0),
        ),
    ]
