# Generated by Django 3.2.9 on 2021-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shareconf", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShareConfiguration",
        ),
        migrations.AddField(
            model_name="project",
            name="cashMultiplier",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="project",
            name="nonCashMultiplier",
            field=models.IntegerField(default=2),
        ),
    ]
